//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalkulatorDostaw.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KalkulatorDostaw.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport will be by bike..
        /// </summary>
        internal static string DeliveryByBike {
            get {
                return ResourceManager.GetString("DeliveryByBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport will be by car..
        /// </summary>
        internal static string DeliveryByCar {
            get {
                return ResourceManager.GetString("DeliveryByCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery will be on foot..
        /// </summary>
        internal static string DeliveryOnFoot {
            get {
                return ResourceManager.GetString("DeliveryOnFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated time is {czas} minutes..
        /// </summary>
        internal static string EstimatedTime {
            get {
                return ResourceManager.GetString("EstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the current weather: 1-sunshine, 2-rain, 3-snow.
        /// </summary>
        internal static string SetActualWeather {
            get {
                return ResourceManager.GetString("SetActualWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the distance (0-10km)..
        /// </summary>
        internal static string SetDistance {
            get {
                return ResourceManager.GetString("SetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the method of transport: 1-on foot, 2-bike, 3-car.
        /// </summary>
        internal static string SetVehicle {
            get {
                return ResourceManager.GetString("SetVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered the distance incorrectly. Enter a value from 0 to 10 (two decimal places are allowed)..
        /// </summary>
        internal static string WrongDistance {
            get {
                return ResourceManager.GetString("WrongDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered the vehicle incorrectly. Enter 1, 2 or 3..
        /// </summary>
        internal static string WrongVehicle {
            get {
                return ResourceManager.GetString("WrongVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered the weather incorrectly. Enter 1, 2 or 3..
        /// </summary>
        internal static string WrongWeather {
            get {
                return ResourceManager.GetString("WrongWeather", resourceCulture);
            }
        }
    }
}
